export { default as Posts } from './posts/PostsView.vue'
export { default as PostUpdate } from './posts/PostUpdate.vue'
export { default as Users } from './users/UsersView.vue'
export { default as UserUpdate } from './users/UserUpdate.vue'
export { default as Products } from './products/ProductsView.vue'
export { default as ProductUpdate } from './products/ProductUpdate.vue'
